// backend/src/config/seedData.js

/**
 * @file Arquivo central para os dados de seed.
 * Contém as categorias padrão e as regras de categorização
 * que serão usadas tanto no `seed.js` quanto na criação de novos usuários.
 */

// Lista de categorias padrão do sistema
export const defaultCategories = [
  // Despesas
  {
    nome: "Alimentacao",
    label: "Alimentação",
    icon: "Utensils",
    type: "despesa",
  },
  {
    nome: "AssinaturasEServicos",
    label: "Assinaturas e Serviços",
    icon: "Wallet",
    type: "despesa",
  },
  {
    nome: "BaresERestaurantes",
    label: "Bares e Restaurantes",
    icon: "GlassWater",
    type: "despesa",
  },
  { nome: "Casa", label: "Casa", icon: "Home", type: "despesa" },
  { nome: "Compras", label: "Compras", icon: "ShoppingCart", type: "despesa" },
  {
    nome: "CuidadosPessoais",
    label: "Cuidados Pessoais",
    icon: "Droplets",
    type: "despesa",
  },
  {
    nome: "DividasEEmprestimos",
    label: "Dívidas e Empréstimos",
    icon: "Landmark",
    type: "despesa",
  },
  {
    nome: "Educacao",
    label: "Educação",
    icon: "GraduationCap",
    type: "despesa",
  },
  {
    nome: "FamiliaEFilhos",
    label: "Família e Filhos",
    icon: "Users",
    type: "despesa",
  },
  {
    nome: "ImpostosETaxas",
    label: "Impostos e Taxas",
    icon: "Landmark",
    type: "despesa",
  },
  {
    nome: "LazerEHobbies",
    label: "Lazer e Hobbies",
    icon: "Gamepad2",
    type: "despesa",
  },
  { nome: "Mercado", label: "Mercado", icon: "ShoppingCart", type: "despesa" },
  { nome: "Outros", label: "Outros", icon: "Tags", type: "despesa" },
  { nome: "Pets", label: "Pets", icon: "Dog", type: "despesa" },
  {
    nome: "PresentesEDoacoes",
    label: "Presentes e Doações",
    icon: "Gift",
    type: "despesa",
  },
  { nome: "Roupas", label: "Roupas", icon: "Shirt", type: "despesa" },
  { nome: "Saude", label: "Saúde", icon: "HeartPulse", type: "despesa" },
  { nome: "Trabalho", label: "Trabalho", icon: "Briefcase", type: "despesa" },
  { nome: "Transporte", label: "Transporte", icon: "Car", type: "despesa" },
  { nome: "Viagem", label: "Viagem", icon: "Plane", type: "despesa" },
  { nome: "Vicios", label: "Vícios", icon: "Flame", type: "despesa" },
  // Receitas
  {
    nome: "Investimentos",
    label: "Investimentos",
    icon: "BarChart",
    type: "receita",
  },
  {
    nome: "Emprestimos",
    label: "Empréstimos",
    icon: "Landmark",
    type: "receita",
  },
  {
    nome: "OutrasReceitas",
    label: "Outras Receitas",
    icon: "DollarSign",
    type: "receita",
  },
  { nome: "Salario", label: "Salário", icon: "Wallet", type: "receita" },
  { nome: "Venda", label: "Venda", icon: "Tag", type: "receita" },
];

// Lista de regras de categorização padrão
export const defaultRules = [
  // Assinaturas e Serviços
  { termo: "Netflix", categoriaNome: "AssinaturasEServicos" },
  { termo: "Spotify", categoriaNome: "AssinaturasEServicos" },
  { termo: "Amazon Prime", categoriaNome: "AssinaturasEServicos" },
  { termo: "Prime Video", categoriaNome: "AssinaturasEServicos" },
  { termo: "HBO Max", categoriaNome: "AssinaturasEServicos" },
  { termo: "Disney+", categoriaNome: "AssinaturasEServicos" },
  { termo: "Globoplay", categoriaNome: "AssinaturasEServicos" },
  { termo: "Youtube Premium", categoriaNome: "AssinaturasEServicos" },
  { termo: "Apple Music", categoriaNome: "AssinaturasEServicos" },
  { termo: "Deezer", categoriaNome: "AssinaturasEServicos" },
  { termo: "Tidal", categoriaNome: "AssinaturasEServicos" },
  { termo: "Uber Pass", categoriaNome: "AssinaturasEServicos" },
  { termo: "iFood Club", categoriaNome: "AssinaturasEServicos" },
  { termo: "Claro", categoriaNome: "AssinaturasEServicos" },
  { termo: "Vivo", categoriaNome: "AssinaturasEServicos" },
  { termo: "Tim", categoriaNome: "AssinaturasEServicos" },
  { termo: "Oi Fibra", categoriaNome: "AssinaturasEServicos" },
  { termo: "Microsoft 365", categoriaNome: "AssinaturasEServicos" },
  { termo: "Adobe", categoriaNome: "AssinaturasEServicos" },
  { termo: "iCloud", categoriaNome: "AssinaturasEServicos" },
  { termo: "Google Drive", categoriaNome: "AssinaturasEServicos" },
  { termo: "Dropbox", categoriaNome: "AssinaturasEServicos" },
  { termo: "Notion", categoriaNome: "AssinaturasEServicos" },
  { termo: "Canva", categoriaNome: "AssinaturasEServicos" },
  { termo: "LinkedIn Premium", categoriaNome: "AssinaturasEServicos" },
  { termo: "Tinder Plus", categoriaNome: "AssinaturasEServicos" },
  { termo: "Playstation Plus", categoriaNome: "LazerEHobbies" },
  { termo: "Xbox Game Pass", categoriaNome: "LazerEHobbies" },
  { termo: "Nintendo Switch Online", categoriaNome: "LazerEHobbies" },
  { termo: "Steam", categoriaNome: "LazerEHobbies" },
  { termo: "Twitch", categoriaNome: "AssinaturasEServicos" },
  { termo: "Kindle Unlimited", categoriaNome: "AssinaturasEServicos" },

  // Mercado
  { termo: "Carrefour", categoriaNome: "Mercado" },
  { termo: "Pao de Acucar", categoriaNome: "Mercado" },
  { termo: "Extra", categoriaNome: "Mercado" },
  { termo: "Assai", categoriaNome: "Mercado" },
  { termo: "Atacadao", categoriaNome: "Mercado" },
  { termo: "Makro", categoriaNome: "Mercado" },
  { termo: "Dia", categoriaNome: "Mercado" },
  { termo: "Supermercado Guanabara", categoriaNome: "Mercado" },
  { termo: "Mundial", categoriaNome: "Mercado" },
  { termo: "Prezunic", categoriaNome: "Mercado" },
  { termo: "Hortifruti", categoriaNome: "Mercado" },
  { termo: "Sonda Supermercados", categoriaNome: "Mercado" },
  { termo: "Zaffari", categoriaNome: "Mercado" },
  { termo: "Bourbon", categoriaNome: "Mercado" },
  { termo: "Angeloni", categoriaNome: "Mercado" },
  { termo: "Hipermercado", categoriaNome: "Mercado" },
  { termo: "Supermercado", categoriaNome: "Mercado" },
  { termo: "Mercado", categoriaNome: "Mercado" },
  { termo: "Mercearia", categoriaNome: "Mercado" },
  { termo: "Sacolao", categoriaNome: "Mercado" },
  { termo: "Feira", categoriaNome: "Mercado" },
  { termo: "Quitanda", categoriaNome: "Mercado" },
  { termo: "Acougue", categoriaNome: "Mercado" },
  { termo: "Padaria", categoriaNome: "Alimentacao" },
  { termo: "Panificadora", categoriaNome: "Alimentacao" },
  { termo: "Swift", categoriaNome: "Mercado" },
  { termo: "Natural da Terra", categoriaNome: "Mercado" },
  { termo: "St Marche", categoriaNome: "Mercado" },

  // Bares e Restaurantes
  { termo: "iFood", categoriaNome: "BaresERestaurantes" },
  { termo: "Rappi", categoriaNome: "BaresERestaurantes" },
  { termo: "Uber Eats", categoriaNome: "BaresERestaurantes" },
  { termo: "McDonald's", categoriaNome: "BaresERestaurantes" },
  { termo: "Burger King", categoriaNome: "BaresERestaurantes" },
  { termo: "Bob's", categoriaNome: "BaresERestaurantes" },
  { termo: "Subway", categoriaNome: "BaresERestaurantes" },
  { termo: "KFC", categoriaNome: "BaresERestaurantes" },
  { termo: "Habibs", categoriaNome: "BaresERestaurantes" },
  { termo: "Giraffas", categoriaNome: "BaresERestaurantes" },
  { termo: "Pizza Hut", categoriaNome: "BaresERestaurantes" },
  { termo: "Domino's", categoriaNome: "BaresERestaurantes" },
  { termo: "Outback", categoriaNome: "BaresERestaurantes" },
  { termo: "Coco Bambu", categoriaNome: "BaresERestaurantes" },
  { termo: "Madero", categoriaNome: "BaresERestaurantes" },
  { termo: "Starbucks", categoriaNome: "BaresERestaurantes" },
  { termo: "Restaurante", categoriaNome: "BaresERestaurantes" },
  { termo: "Lanchonete", categoriaNome: "BaresERestaurantes" },
  { termo: "Pizzaria", categoriaNome: "BaresERestaurantes" },
  { termo: "Churrascaria", categoriaNome: "BaresERestaurantes" },
  { termo: "Bar", categoriaNome: "BaresERestaurantes" },
  { termo: "Cafe", categoriaNome: "BaresERestaurantes" },
  { termo: "Sorveteria", categoriaNome: "BaresERestaurantes" },
  { termo: "Doceria", categoriaNome: "BaresERestaurantes" },
  { termo: "Cervejaria", categoriaNome: "BaresERestaurantes" },
  { termo: "Adega", categoriaNome: "BaresERestaurantes" },

  // Saúde
  { termo: "Drogasil", categoriaNome: "Saude" },
  { termo: "Droga Raia", categoriaNome: "Saude" },
  { termo: "Pacheco", categoriaNome: "Saude" },
  { termo: "Drogaria Sao Paulo", categoriaNome: "Saude" },
  { termo: "Ultrafarma", categoriaNome: "Saude" },
  { termo: "Unimed", categoriaNome: "Saude" },
  { termo: "Amil", categoriaNome: "Saude" },
  { termo: "Bradesco Saude", categoriaNome: "Saude" },
  { termo: "SulAmerica", categoriaNome: "Saude" },
  { termo: "Hapvida", categoriaNome: "Saude" },
  { termo: "Fleury", categoriaNome: "Saude" },
  { termo: "Lavoisier", categoriaNome: "Saude" },
  { termo: "Delboni Auriemo", categoriaNome: "Saude" },
  { termo: "Hospital", categoriaNome: "Saude" },
  { termo: "Clinica", categoriaNome: "Saude" },
  { termo: "Laboratorio", categoriaNome: "Saude" },
  { termo: "Farmacia", categoriaNome: "Saude" },
  { termo: "Drogaria", categoriaNome: "Saude" },
  { termo: "Consulta", categoriaNome: "Saude" },
  { termo: "Exame", categoriaNome: "Saude" },
  { termo: "Remedio", categoriaNome: "Saude" },
  { termo: "Medicamento", categoriaNome: "Saude" },
  { termo: "Plano de Saude", categoriaNome: "Saude" },
  { termo: "Odonto", categoriaNome: "Saude" },
  { termo: "Dentista", categoriaNome: "Saude" },
  { termo: "Terapia", categoriaNome: "Saude" },
  { termo: "Psicologo", categoriaNome: "Saude" },

  // Transporte
  { termo: "Uber", categoriaNome: "Transporte" },
  { termo: "99", categoriaNome: "Transporte" },
  { termo: "Cabify", categoriaNome: "Transporte" },
  { termo: "Posto Ipiranga", categoriaNome: "Transporte" },
  { termo: "Shell", categoriaNome: "Transporte" },
  { termo: "Petrobras", categoriaNome: "Transporte" },
  { termo: "Ale", categoriaNome: "Transporte" },
  { termo: "Combustivel", categoriaNome: "Transporte" },
  { termo: "Gasolina", categoriaNome: "Transporte" },
  { termo: "Etanol", categoriaNome: "Transporte" },
  { termo: "Diesel", categoriaNome: "Transporte" },
  { termo: "Estacionamento", categoriaNome: "Transporte" },
  { termo: "Zona Azul", categoriaNome: "Transporte" },
  { termo: "Pedagio", categoriaNome: "Transporte" },
  { termo: "Sem Parar", categoriaNome: "Transporte" },
  { termo: "ConectCar", categoriaNome: "Transporte" },
  { termo: "Veloe", categoriaNome: "Transporte" },
  { termo: "Onibus", categoriaNome: "Transporte" },
  { termo: "Metro", categoriaNome: "Transporte" },
  { termo: "Bilhete Unico", categoriaNome: "Transporte" },
  { termo: "Recarga", categoriaNome: "Transporte" },
  { termo: "Manutencao", categoriaNome: "Transporte" },
  { termo: "Oficina", categoriaNome: "Transporte" },
  { termo: "Troca de Oleo", categoriaNome: "Transporte" },
  { termo: "Pneu", categoriaNome: "Transporte" },
  { termo: "Seguro Auto", categoriaNome: "Transporte" },
  { termo: "Porto Seguro", categoriaNome: "Transporte" },

  // Compras
  { termo: "Amazon", categoriaNome: "Compras" },
  { termo: "Mercado Livre", categoriaNome: "Compras" },
  { termo: "Shopee", categoriaNome: "Compras" },
  { termo: "AliExpress", categoriaNome: "Compras" },
  { termo: "Magazine Luiza", categoriaNome: "Compras" },
  { termo: "Magalu", categoriaNome: "Compras" },
  { termo: "Casas Bahia", categoriaNome: "Compras" },
  { termo: "Ponto Frio", categoriaNome: "Compras" },
  { termo: "Americanas", categoriaNome: "Compras" },
  { termo: "Kalunga", categoriaNome: "Compras" },
  { termo: "Leroy Merlin", categoriaNome: "Casa" },
  { termo: "Telhanorte", categoriaNome: "Casa" },
  { termo: "Daiso", categoriaNome: "Compras" },
  { termo: "Miniso", categoriaNome: "Compras" },
  { termo: "Livraria Cultura", categoriaNome: "Educacao" },
  { termo: "Saraiva", categoriaNome: "Educacao" },
  { termo: "Decathlon", categoriaNome: "LazerEHobbies" },
  { termo: "Centauro", categoriaNome: "LazerEHobbies" },
  { termo: "Apple Store", categoriaNome: "Compras" },
  { termo: "Samsung", categoriaNome: "Compras" },
  { termo: "Fast Shop", categoriaNome: "Compras" },
  { termo: "Polishop", categoriaNome: "Compras" },
  { termo: "Shopping", categoriaNome: "Compras" },
  { termo: "Eletronicos", categoriaNome: "Compras" },
  { termo: "Papelaria", categoriaNome: "Educacao" },

  // Casa
  { termo: "Enel", categoriaNome: "Casa" },
  { termo: "Light", categoriaNome: "Casa" },
  { termo: "Eletropaulo", categoriaNome: "Casa" },
  { termo: "Sabesp", categoriaNome: "Casa" },
  { termo: "Cedae", categoriaNome: "Casa" },
  { termo: "Comgas", categoriaNome: "Casa" },
  { termo: "Conta de Luz", categoriaNome: "Casa" },
  { termo: "Conta de Agua", categoriaNome: "Casa" },
  { termo: "Conta de Gas", categoriaNome: "Casa" },
  { termo: "Aluguel", categoriaNome: "Casa" },
  { termo: "Condominio", categoriaNome: "Casa" },
  { termo: "Internet", categoriaNome: "AssinaturasEServicos" },
  { termo: "TV a Cabo", categoriaNome: "AssinaturasEServicos" },
  { termo: "Faxina", categoriaNome: "Casa" },
  { termo: "Diarista", categoriaNome: "Casa" },
  { termo: "Reforma", categoriaNome: "Casa" },
  { termo: "Decoracao", categoriaNome: "Casa" },
  { termo: "Tok&Stok", categoriaNome: "Casa" },
  { termo: "Etna", categoriaNome: "Casa" },
  { termo: "Mobly", categoriaNome: "Casa" },
  { termo: "MadeiraMadeira", categoriaNome: "Casa" },

  // Lazer e Hobbies
  { termo: "Cinema", categoriaNome: "LazerEHobbies" },
  { termo: "Cinemark", categoriaNome: "LazerEHobbies" },
  { termo: "UCI", categoriaNome: "LazerEHobbies" },
  { termo: "Kinoplex", categoriaNome: "LazerEHobbies" },
  { termo: "Show", categoriaNome: "LazerEHobbies" },
  { termo: "Teatro", categoriaNome: "LazerEHobbies" },
  { termo: "Ingresso", categoriaNome: "LazerEHobbies" },
  { termo: "Sympla", categoriaNome: "LazerEHobbies" },
  { termo: "Eventim", categoriaNome: "LazerEHobbies" },
  { termo: "Ticketmaster", categoriaNome: "LazerEHobbies" },
  { termo: "Clube", categoriaNome: "LazerEHobbies" },
  { termo: "Academia", categoriaNome: "Saude" },
  { termo: "Smart Fit", categoriaNome: "Saude" },
  { termo: "Bodytech", categoriaNome: "Saude" },
  { termo: "Bluefit", categoriaNome: "Saude" },
  { termo: "Hobby", categoriaNome: "LazerEHobbies" },
  { termo: "Jogo", categoriaNome: "LazerEHobbies" },
  { termo: "Game", categoriaNome: "LazerEHobbies" },
  { termo: "Parque", categoriaNome: "LazerEHobbies" },
  { termo: "Praia", categoriaNome: "LazerEHobbies" },
  { termo: "Passeio", categoriaNome: "LazerEHobbies" },

  // Viagem
  { termo: "Decolar", categoriaNome: "Viagem" },
  { termo: "Booking", categoriaNome: "Viagem" },
  { termo: "Airbnb", categoriaNome: "Viagem" },
  { termo: "CVC", categoriaNome: "Viagem" },
  { termo: "LATAM", categoriaNome: "Viagem" },
  { termo: "GOL", categoriaNome: "Viagem" },
  { termo: "Azul", categoriaNome: "Viagem" },
  { termo: "Passagem Aerea", categoriaNome: "Viagem" },
  { termo: "Hotel", categoriaNome: "Viagem" },
  { termo: "Hospedagem", categoriaNome: "Viagem" },
  { termo: "Aluguel de Carro", categoriaNome: "Viagem" },
  { termo: "Localiza", categoriaNome: "Viagem" },
  { termo: "Movida", categoriaNome: "Viagem" },
  { termo: "Unidas", categoriaNome: "Viagem" },
  { termo: "Mala", categoriaNome: "Viagem" },
  { termo: "Agencia de Viagem", categoriaNome: "Viagem" },
  { termo: "Intercambio", categoriaNome: "Viagem" },
  { termo: "Resort", categoriaNome: "Viagem" },

  // Roupas
  { termo: "C&A", categoriaNome: "Roupas" },
  { termo: "Renner", categoriaNome: "Roupas" },
  { termo: "Riachuelo", categoriaNome: "Roupas" },
  { termo: "Zara", categoriaNome: "Roupas" },
  { termo: "H&M", categoriaNome: "Roupas" },
  { termo: "Dafiti", categoriaNome: "Roupas" },
  { termo: "Zattini", categoriaNome: "Roupas" },
  { termo: "Posthaus", categoriaNome: "Roupas" },
  { termo: "Nike", categoriaNome: "Roupas" },
  { termo: "Adidas", categoriaNome: "Roupas" },
  { termo: "Puma", categoriaNome: "Roupas" },
  { termo: "Calcado", categoriaNome: "Roupas" },
  { termo: "Tenis", categoriaNome: "Roupas" },
  { termo: "Camisa", categoriaNome: "Roupas" },
  { termo: "Calca", categoriaNome: "Roupas" },
  { termo: "Vestido", categoriaNome: "Roupas" },

  // Cuidados Pessoais
  { termo: "Cabeleireiro", categoriaNome: "CuidadosPessoais" },
  { termo: "Salao de Beleza", categoriaNome: "CuidadosPessoais" },
  { termo: "Barbearia", categoriaNome: "CuidadosPessoais" },
  { termo: "Manicure", categoriaNome: "CuidadosPessoais" },
  { termo: "Pedicure", categoriaNome: "CuidadosPessoais" },
  { termo: "Estetica", categoriaNome: "CuidadosPessoais" },
  { termo: "Massagem", categoriaNome: "CuidadosPessoais" },
  { termo: "Spa", categoriaNome: "CuidadosPessoais" },
  { termo: "Cosmeticos", categoriaNome: "CuidadosPessoais" },
  { termo: "Perfumaria", categoriaNome: "CuidadosPessoais" },
  { termo: "Sephora", categoriaNome: "CuidadosPessoais" },
  { termo: "O Boticario", categoriaNome: "CuidadosPessoais" },
  { termo: "Natura", categoriaNome: "CuidadosPessoais" },

  // Educação
  { termo: "Escola", categoriaNome: "Educacao" },
  { termo: "Colegio", categoriaNome: "Educacao" },
  { termo: "Faculdade", categoriaNome: "Educacao" },
  { termo: "Universidade", categoriaNome: "Educacao" },
  { termo: "Curso", categoriaNome: "Educacao" },
  { termo: "Udemy", categoriaNome: "Educacao" },
  { termo: "Coursera", categoriaNome: "Educacao" },
  { termo: "Alura", categoriaNome: "Educacao" },
  { termo: "Hotmart", categoriaNome: "Educacao" },
  { termo: "Livro", categoriaNome: "Educacao" },
  { termo: "Material Escolar", categoriaNome: "Educacao" },
  { termo: "Mensalidade", categoriaNome: "Educacao" },

  // Pets
  { termo: "Petz", categoriaNome: "Pets" },
  { termo: "Cobasi", categoriaNome: "Pets" },
  { termo: "Pet Shop", categoriaNome: "Pets" },
  { termo: "Veterinario", categoriaNome: "Pets" },
  { termo: "Racao", categoriaNome: "Pets" },
  { termo: "Banho e Tosa", categoriaNome: "Pets" },
  { termo: "Brinquedo Pet", categoriaNome: "Pets" },

  // Família e Filhos
  { termo: "Fralda", categoriaNome: "FamiliaEFilhos" },
  { termo: "Leite em Po", categoriaNome: "FamiliaEFilhos" },
  { termo: "Creche", categoriaNome: "FamiliaEFilhos" },
  { termo: "Baba", categoriaNome: "FamiliaEFilhos" },
  { termo: "Brinquedo", categoriaNome: "FamiliaEFilhos" },
  { termo: "Mesada", categoriaNome: "FamiliaEFilhos" },
  { termo: "Presente Dia das Criancas", categoriaNome: "FamiliaEFilhos" },

  // Dívidas e Empréstimos
  { termo: "Financiamento", categoriaNome: "DividasEEmprestimos" },
  { termo: "Emprestimo", categoriaNome: "DividasEEmprestimos" },
  { termo: "Juros", categoriaNome: "DividasEEmprestimos" },
  { termo: "Parcela", categoriaNome: "DividasEEmprestimos" },
  { termo: "Acordo", categoriaNome: "DividasEEmprestimos" },
  { termo: "Divida", categoriaNome: "DividasEEmprestimos" },

  // Impostos e Taxas
  { termo: "IPTU", categoriaNome: "ImpostosETaxas" },
  { termo: "IPVA", categoriaNome: "ImpostosETaxas" },
  { termo: "Imposto de Renda", categoriaNome: "ImpostosETaxas" },
  { termo: "DARF", categoriaNome: "ImpostosETaxas" },
  { termo: "Taxa", categoriaNome: "ImpostosETaxas" },
  { termo: "Multa", categoriaNome: "ImpostosETaxas" },

  // Receitas
  { termo: "Salario", categoriaNome: "Salario" },
  { termo: "Pagamento", categoriaNome: "Salario" },
  { termo: "Adiantamento", categoriaNome: "Salario" },
  { termo: "Decimo Terceiro", categoriaNome: "Salario" },
  { termo: "Ferias", categoriaNome: "Salario" },
  { termo: "Bonus", categoriaNome: "OutrasReceitas" },
  { termo: "PLR", categoriaNome: "OutrasReceitas" },
  { termo: "Restituicao IR", categoriaNome: "OutrasReceitas" },
  { termo: "Rendimento", categoriaNome: "Investimentos" },
  { termo: "Dividendo", categoriaNome: "Investimentos" },
  { termo: "JCP", categoriaNome: "Investimentos" },
  { termo: "Venda", categoriaNome: "Venda" },
  { termo: "Pix Recebido", categoriaNome: "OutrasReceitas" },
  { termo: "Transferencia Recebida", categoriaNome: "OutrasReceitas" },
  { termo: "Reembolso", categoriaNome: "OutrasReceitas" },
  { termo: "Cashback", categoriaNome: "OutrasReceitas" },
  { termo: "Credito", categoriaNome: "OutrasReceitas" },
  { termo: "Presente", categoriaNome: "PresentesEDoacoes" },
  { termo: "Doacao Recebida", categoriaNome: "PresentesEDoacoes" },
];
